### ISSUE TITLE
Dialyzer error

### ISSUE THREAD

**Issue by gf3** [zachallaun/janus#1]
I'm seeing a dialyzer error when using `Janus.Policy.allow/3`:

![error](https://screenshot.pics/s/_eldoc-box_2023-02-13_22-39-55.png)

If I instead call `allow/4` with an empty keyword list, the error goes away:

![no error](https://screenshot.pics/s/policy.ex_2023-02-13_22-42-30.png)

I'm no dialyzer expert, but if I had to guess it's because [`allow/3` is missing a `@spec`](https://github.com/zachallaun/ex_janus/blob/b9516772e51b2c673fdf7a97c45f9840d085c511/lib/janus/policy.ex#L317-L320)

**Comment by zachallaun** [comment]
Thanks for the report! I've published [v0.3.2](https://hex.pm/packages/ex_janus/0.3.2) which fixes the issue.

I'll think of a better way to test/verify this going forward. This project is tested pretty comprehensively, but tests aren't run through Dialyzer. I may try to refactor a portion of unit tests to be "integration tests" such that can can be compiled/evaluated by Dialyzer, and then just make sure that those integration tests hit all of the public API usage to catch out Dialyzer errors.

**Comment by gf3** [comment]
thank you @zachallaun 👐
